### ISSUE TITLE
请问这个支持openai的access token么？还是只支持api？

### ISSUE THREAD

**Issue by justincnn** [jarvis2f/ais-ninja#1]
你的demo，没有管理页面的演示，还请告知，谢谢

**Comment by jarvis2f** [comment]
@justincnn 现在只支持key

**Comment by justincnn** [comment]
> @justincnn 现在只支持key

嗯嗯，谢谢哦，

请问可以支持access token么？

**Comment by jarvis2f** [comment]
@justincnn 现在用的openai官方的nodejs Library，只支持apiKey的方式。
