### ISSUE TITLE
看起来不支持打字回复效果

### ISSUE THREAD

**Issue by lokewei** [jarvis2f/ais-ninja#11]
更正：用docker部署了一套，测试没发现这个效果。 但是看演示站点是支持的，是否有什么配置要启用 :)

**Comment by jarvis2f** [comment]
支持的大兄弟

**Comment by jarvis2f** [comment]
好像不用做啥配置的

**Comment by lokewei** [comment]
![Kapture 2023-07-20 at 11 18 11](https://github.com/jarvis2f/ais-ninja/assets/1223119/88a2015f-eb24-4e62-9635-3d223881c039)
录了个gif

**Comment by jarvis2f** [comment]
SERVER_LOG_LEVEL: 'debug' 加个debug，看看日志输出是不是stream的

**Comment by lokewei** [comment]
知道原因了，是nginx反向代理层需要提供sse的支持（我的错） ，参考：https://gist.github.com/yllan/4712935
