### ISSUE TITLE
如何实现一次请求调用多个函数或者多次函数

### ISSUE THREAD

**Issue by spldmanager** [jarvis2f/ais-ninja#4]
我看了下官方的文档，可以传入多个函数，但是一次对话只能返回一个函数调用，例如我传入a\b\c三个函数，chatgpt只能返回调用a函数。而且以ip查询为例，用你提供的插件函数，我试了官方接口，一次对话只能调用函数一次传入参数一个，请问你是怎么实现2个IP查询的？

**Comment by jarvis2f** [comment]
这个是由gpt决定的，ip查询调用两次是因为第一次函数返回给gpt后，gpt返回还是调用函数。要自己决定就是将函数的参数改为数组，自己实现调用多次了。

**Comment by spldmanager** [comment]
我用你的Ipinfo插件，它的传入参数是{ip: ip}对象，当我对话给gpt说我要查a和b的ip的时候，它给我返回的是调用search_ip这个函数，参数只有{ip:a}并没有返回给我b
我现在能想到的是把search_ip的传入参数改成{ip:[]}，我预计这样gpt才会给我返回参数是{ip:[a,b]}。但是我看你的插件函数并不是这样写的，所以我也不知道你是怎么实现的

**Comment by jarvis2f** [comment]
第一次调用结束后，gpt下一次返回内容还是调用函数的。

**Comment by spldmanager** [comment]
感谢指点，看了下是因为自己在第二次发送给gpt的时候，没带上它第一次返回的message。
