### ISSUE TITLE
数据库同步失效

### ISSUE THREAD

**Issue by sth0409** [jarvis2f/ais-ninja#6]
设置了DATABASE_SYNC='true'参数，但是数据库表没有自动创建，是怎么回事呢？求解答

**Comment by jarvis2f** [comment]
日志有吗

**Comment by sth0409** [comment]
![image](https://github.com/jarvis2f/ais-ninja/assets/19368488/3adc7355-11b7-43e4-a1e9-b35f26ef7c96)
![image](https://github.com/jarvis2f/ais-ninja/assets/19368488/4bc4ebcf-c958-4dcc-bc9e-6991eec08fd9)
只有这些

**Comment by jarvis2f** [comment]
正常同步会输出日志：Database synced
看看数据库配置对不对，把库删了重新跑一遍试试。

**Comment by sth0409** [comment]
嗯嗯 好的  我再研究研究

**Comment by sth0409** [comment]
发现问题了   DATABASE_SYNC='true' 不能带引号
